In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_csv("/content/50_Startups.csv")

In [ ]:
df

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42  California  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68    New York  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95  California  146121.95
11  100671.96        91790.61        249744.55     Florida  144259.40
12   93863.75       127320.38        249839.44  California  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57    New York  124266.90
19   86419.70       153514.11             0.00     Florida  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26  California  110352.25
23   67532.53       105751.03        304768.73  California  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07    New York  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24    New York   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81    New York   96778.92
34   46426.07       157693.92        210797.67     Florida   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82    New York   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67     Florida   78239.91
41   27892.92        84710.77        164470.71  California   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [ ]:
x = df.iloc[:, :-1].values
y = df.iloc[:, 4].values

In [ ]:
print(x,y)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'California']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'New York']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'California']
 [100671.96 91790.61 249744.55 'Florida']
 [93863.75 127320.38 249839.44 'California']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'New York']
 [86419.7 153514.11 0.0 'Florida']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'California

In [ ]:
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42  California  166187.94

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
Label = LabelEncoder()
x[:, 3] = Label.fit_transform(x[:, 3])
print(x)

[[165349.2 136897.8 471784.1 2]
 [162597.7 151377.59 443898.53 0]
 [153441.51 101145.55 407934.54 1]
 [144372.41 118671.85 383199.62 2]
 [142107.34 91391.77 366168.42 0]
 [131876.9 99814.71 362861.36 2]
 [134615.46 147198.87 127716.82 0]
 [130298.13 145530.06 323876.68 2]
 [120542.52 148718.95 311613.29 2]
 [123334.88 108679.17 304981.62 0]
 [101913.08 110594.11 229160.95 0]
 [100671.96 91790.61 249744.55 1]
 [93863.75 127320.38 249839.44 0]
 [91992.39 135495.07 252664.93 0]
 [119943.24 156547.42 256512.92 1]
 [114523.61 122616.84 261776.23 2]
 [78013.11 121597.55 264346.06 0]
 [94657.16 145077.58 282574.31 2]
 [91749.16 114175.79 294919.57 2]
 [86419.7 153514.11 0.0 1]
 [76253.86 113867.3 298664.47 0]
 [78389.47 153773.43 299737.29 2]
 [73994.56 122782.75 303319.26 0]
 [67532.53 105751.03 304768.73 0]
 [77044.01 99281.34 140574.81 2]
 [64664.71 139553.16 137962.62 0]
 [75328.87 144135.98 134050.07 2]
 [72107.6 127864.55 353183.81 2]
 [66051.52 182645.56 118148.2 1]
 [65605.48 153032.0

In [ ]:
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([('encoder',OneHotEncoder(),[3])],remainder='passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [1.0 0.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 0.0 1.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [1.0 0.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 100671.96 91790.61 249744.55]
 [1.0 0.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 0.0 1.0 91749.16 114175.79 294919.57]
 [0.0 1.0 0.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [1.0 0.0 0.0 73994.56 122782.75 3

In [ ]:
print(ord('a'))
print(chr(97))

97
a


In [ ]:
a = "encrypt this message using python"
encrypted_message=" "
for i in a:
  if i.isalpha():
    encrypted_message+=chr(219-ord(i))
  elif i==" ":
    encrypted_message+="**"
  else:
    encrypted_message+=i
print(encrypted_message)

 vmxibkg**gsrh**nvhhztv**fhrmt**kbgslm


In [ ]:
message="vmxibkg*gsrh*fhrmt*kbgslm!"
decrypted_message=""
for i in message:
  if i.isalpha():
    decrypted_message+=chr(219-ord(i))
  elif i==" ":
    decrypted_message+="**"
  else:
    decrypted_message+=i
print(decrypted_message)

encrypt*this*using*python!


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=14)

In [ ]:
print(x.shape)
print(y.shape)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(50, 6)
(50,)
(40, 6)
(10, 6)
(40,)
(10,)


In [ ]:
from sklearn.linear_model import LinearRegression
l=LinearRegression()
l=l.fit(x_train,y_train)
l

LinearRegression()

In [ ]:
y_pred=l.predict(x_test)
y_pred

array([ 46992.29340222, 118113.93670712, 152546.84491681,  99206.91723847,
        87945.53013535,  77273.68551212, 118522.64975353, 189567.93038268,
       183707.23325005, 158307.55876047])

In [ ]:
y_test

array([ 42559.73, 111313.02, 132602.65,  99937.59,  89949.14,  78239.91,
       122776.86, 191792.06, 191050.39, 156122.51])

In [ ]:
result=pd.concat([pd.DataFrame(y_pred,columns=['Prediction']),
                  pd.DataFrame(y_test,columns=['Test'])],axis=1)
result['Difference']=result['Prediction']-result['Test']
result

Prediction       Test    Difference
0   46992.293402   42559.73   4432.563402
1  118113.936707  111313.02   6800.916707
2  152546.844917  132602.65  19944.194917
3   99206.917238   99937.59   -730.672762
4   87945.530135   89949.14  -2003.609865
5   77273.685512   78239.91   -966.224488
6  118522.649754  122776.86  -4254.210246
7  189567.930383  191792.06  -2224.129617
8  183707.233250  191050.39  -7343.156750
9  158307.558760  156122.51   2185.048760

In [ ]:
r2_score(y_test,y_pred)

0.973474954355189

In [ ]:
y_final_pred=l.predict(x)
y_final_pred

array([192577.5936131 , 189567.93038268, 183707.23325005, 173334.25307143,
       171093.01766635, 162795.31959542, 158307.55876047, 160356.36676279,
       152197.73705584, 154319.25773265, 135041.77592031, 137046.83963992,
       129148.83111479, 127715.54946377, 152546.84491681, 146028.49357839,
       116878.25108624, 130669.5842267 , 128743.35102725, 118522.64975353,
       116446.53136456, 118113.93670712, 114752.71224431, 109651.22374275,
       112669.56876675, 102616.16692774, 111033.53776076, 114631.09644782,
       105481.00894923, 102479.60216101,  99206.91723847,  98372.14228427,
        99052.0934655 ,  97490.44026376,  92415.21124119,  89678.59702284,
        75592.29185814,  87945.53013535,  68505.31333552,  82859.2808048 ,
        77273.68551212,  74023.52399789,  70137.50109257,  60414.2085062 ,
        65504.7985268 ,  47865.59922452,  58802.27016968,  46992.29340222,
        47574.76343749,  48292.39484897])

In [ ]:
y_fpred=pd.DataFrame(y_final_pred,columns=['Prediction'])
result=pd.concat([df,y_fpred],axis=1)
result['Difference']=result['Profit']-result['Prediction']
result

R&D Spend  Administration  Marketing Spend       State     Profit  \
0   165349.20       136897.80        471784.10    New York  192261.83   
1   162597.70       151377.59        443898.53  California  191792.06   
2   153441.51       101145.55        407934.54     Florida  191050.39   
3   144372.41       118671.85        383199.62    New York  182901.99   
4   142107.34        91391.77        366168.42  California  166187.94   
5   131876.90        99814.71        362861.36    New York  156991.12   
6   134615.46       147198.87        127716.82  California  156122.51   
7   130298.13       145530.06        323876.68    New York  155752.60   
8   120542.52       148718.95        311613.29    New York  152211.77   
9   123334.88       108679.17        304981.62  California  149759.96   
10  101913.08       110594.11        229160.95  California  146121.95   
11  100671.96        91790.61        249744.55     Florida  144259.40   
12   93863.75       127320.38        249839.44  California  141585.52   
13   91992.39       135495.07        252664.93  California  134307.35   
14  119943.24       156547.42        256512.92     Florida  132602.65   
15  114523.61       122616.84        261776.23    New York  129917.04   
16   78013.11       121597.55        264346.06  California  126992.93   
17   94657.16       145077.58        282574.31    New York  125370.37   
18   91749.16       114175.79        294919.57    New York  124266.90   
19   86419.70       153514.11             0.00     Florida  122776.86   
20   76253.86       113867.30        298664.47  California  118474.03   
21   78389.47       153773.43        299737.29    New York  111313.02   
22   73994.56       122782.75        303319.26  California  110352.25   
23   67532.53       105751.03        304768.73  California  108733.99   
24   77044.01        99281.34        140574.81    New York  108552.04   
25   64664.71       139553.16        137962.62  California  107404.34   
26   75328.87       144135.98        134050.07    New York  105733.54   
27   72107.60       127864.55        353183.81    New York  105008.31   
28   66051.52       182645.56        118148.20     Florida  103282.38   
29   65605.48       153032.06        107138.38    New York  101004.64   
30   61994.48       115641.28         91131.24    New York   99937.59   
31   61136.38       152701.92         88218.23    New York   97483.56   
32   63408.86       129219.61         46085.25  California   97427.84   
33   55493.95       103057.49        214634.81    New York   96778.92   
34   46426.07       157693.92        210797.67     Florida   96712.80   
35   46014.02        85047.44        205517.64    New York   96479.51   
36   28663.76       127056.21        201126.82    New York   90708.19   
37   44069.95        51283.14        197029.42  California   89949.14   
38   20229.59        65947.93        185265.10    New York   81229.06   
39   38558.51        82982.09        174999.30  California   81005.76   
40   28754.33       118546.05        172795.67     Florida   78239.91   
41   27892.92        84710.77        164470.71  California   77798.83   
42   23640.93        96189.63        148001.11  California   71498.49   
43   15505.73       127382.30         35534.17    New York   69758.98   
44   22177.74       154806.14         28334.72  California   65200.33   
45    1000.23       124153.04          1903.93    New York   64926.08   
46    1315.46       115816.21        297114.46     Florida   49490.75   
47       0.00       135426.92             0.00  California   42559.73   
48     542.05        51743.15             0.00    New York   35673.41   
49       0.00       116983.80         45173.06  California   14681.40   

       Prediction    Difference  
0   192577.593613   -315.763613  
1   189567.930383   2224.129617  
2   183707.233250   7343.156750  
3   173334.253071   9567.736929  
4   171093.017666  -4905.077666  
5   162795.319595  -5804.199595  
6   158307.558760  -2185.048760  
7   1603